version: 2
jobs:
  build:
    machine: true
    steps:
      # ...
      - run:
          name: Build image
          command: |
            ls -lR
      - run:
          name: Build image
          command: docker build -f ../../ 
      - run:
          name: Test image
          command: |
            docker run -d -p 8080:8080 --name built-image test
