version: 2
jobs:
  build:
    machine: true
    steps:
      # ...
      - run:
          name: Build image
          command: |
            git clone https://github.com/semopuri/test.git
      - run:
          name: Build image
          command: docker build -t test -f /home/circleci/project/test/Dockerfile
      - run:
          name: Test image
          command: |
            docker run -d -p 8080:8080 --name built-image test
