version: 2
jobs:
  build:
    machine: true
    steps:
      # ...
      - run:
          name: Build image
          command: |
            git clone https://github.com/semopuri/test.git
      - run:
          name: Build image
          working_directory: test
          command: docker build -t test-docker .
      - run:
          name: Test image
          command: |
            docker run -d -p 8080:8080 --name built-image test-docker
      - run:
          name: Create ECR repository
          command: |
            aws ecr create-repository --repository-name hello-repository
      - run:
          name: Docker Tag Images
          command: |
            docker tag test-docker ${aws_account_id}.dkr.ecr.us-east-1.amazonaws.com/hello-repository
      - run:
          name: AWS ECR Login
          command: |
            eval $(aws ecr get-login --no-include-email)
      - run:
          name: Docker push
          command: |
            docker push ${aws_account_id}.dkr.ecr.us-east-1.amazonaws.com/hello-repository
